# Generated by Django 3.2.9 on 2021-11-16 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post_comentarios', '0004_alter_comentario_user'),
        ('Post_noticias', '0005_alter_postagem_user'),
        ('user_perfil', '0003_auto_20211116_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Perfil_Usuario',
        ),
    ]
