# Generated by Django 3.2.9 on 2021-11-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_perfil', '0004_rename_usuario_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={},
        ),
    ]
