# Generated by Django 3.2.9 on 2021-11-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_perfil', '0005_alter_perfil_usuario_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
