# Generated by Django 3.2.9 on 2021-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0004_alter_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
