# Generated by Django 3.2.9 on 2021-11-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_perfil', '0007_alter_perfil_usuario_user'),
        ('Post_comentarios', '0005_auto_20211117_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_perfil.perfil_usuario'),
        ),
    ]
