# Generated by Django 3.2.9 on 2021-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0006_alter_comentario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
