# Generated by Django 3.2.9 on 2021-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0008_alter_comentario_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.URLField(blank=True, null=True),
        ),
    ]
