# Generated by Django 3.2.9 on 2021-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0009_alter_comentario_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='img_perfil',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='comentario',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
