# Generated by Django 3.2.9 on 2021-11-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post_noticias', '0006_auto_20211117_2320'),
        ('Post_comentarios', '0010_auto_20211117_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='postagem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post_noticias.postagem'),
        ),
    ]
