# Generated by Django 3.2.9 on 2021-11-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0011_comentario_postagem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
    ]
