# Generated by Django 3.2.9 on 2021-11-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_comentarios', '0012_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome_user',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
