# Generated by Django 3.2.9 on 2021-11-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_noticias', '0002_auto_20211116_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
