# Generated by Django 3.2.9 on 2021-11-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_perfil', '0002_auto_20211116_1525'),
        ('Post_noticias', '0004_alter_postagem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_perfil.usuario'),
        ),
    ]
