# Generated by Django 3.2.9 on 2021-11-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_noticias', '0005_alter_postagem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='state',
        ),
    ]
