# Generated by Django 3.2.9 on 2021-11-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_noticias', '0007_postagem_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
