# Generated by Django 3.2.9 on 2021-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_noticias', '0008_postagem_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='fonte_original',
            field=models.CharField(blank=True, default='não informado', max_length=200, null=True),
        ),
    ]
